In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import zipfile
import os

import pandas as pd

working_folder='/content/drive/My Drive/TransformersCode/03-restaurant/Find_meals/'

zip_file_path = working_folder +'indian_food.zip'

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(working_folder)

csv_file_path = os.path.join(working_folder, 'indian_food.csv')
df = pd.read_csv(csv_file_path)

df.head()

name         ARname  \
0      Balu shahi      بالو شاهي   
1          Boondi          بوندي   
2  Gajar ka halwa  جاجار كا حلوة   
3          Ghevar          غيفار   
4      Gulab beef       جلاب بقر   

                                         ingredients  \
0                    Maida flour, yogurt, oil, sugar   
1                            Gram flour, ghee, sugar   
2       Carrots, milk, sugar, ghee, cashews, raisins   
3  Flour, ghee, kewra, milk, clarified butter, su...   
4  Milk powder, plain flour, baking powder, ghee,...   

                                       ARingredients        diet ARdiet  \
0                        دقيق مائدة، زبادي، زيت، سكر  vegetarian  نباتي   
1                                جرام دقيق، سمن، سكر  vegetarian  نباتي   
2                    جزر، حليب، سكر، سمن، كاجو، زبيب  vegetarian  نباتي   
3  طحين، سمن، كيورا، حليب، زبدة، سكر، لوز، فستق، ...  vegetarian  نباتي   
4  حليب بودرة ، دقيق عادي ، بيكنج باودر ، سمن ، ح...  vegetarian  نباتي   

   prep_time  cook_time flavor_profile   course ARflavor_profile ARcourse  \
0         45         25          sweet  dessert              حلو    تحلية   
1         80         30          sweet  dessert              حلو    تحلية   
2         15         60          sweet  dessert              حلو    تحلية   
3         15         30          sweet  dessert              حلو    تحلية   
4         15         40          sweet  dessert              حلو    تحلية   

         state region  
0  West Bengal   East  
1    Rajasthan   West  
2       Punjab  North  
3    Rajasthan   West  
4  West Bengal   East

In [3]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/distiluse-base-multilingual-cased-v1')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/341 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.47k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/556 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/452 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

2_Dense/config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

In [4]:
embeddings = model.encode(df['ARingredients'])
print(embeddings.shape)

(255, 512)


In [5]:
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(embeddings, embeddings)
print(similarities.shape)
print(similarities)

(255, 255)
[[1.0000001  0.6945308  0.61966586 ... 0.3559543  0.24791378 0.23562291]
 [0.6945308  1.         0.68130034 ... 0.4211163  0.3362406  0.24663337]
 [0.61966586 0.68130034 1.         ... 0.442216   0.42944115 0.32536662]
 ...
 [0.3559543  0.4211163  0.442216   ... 1.0000001  0.539516   0.35049137]
 [0.24791378 0.3362406  0.42944115 ... 0.539516   1.         0.41640878]
 [0.23562291 0.24663337 0.32536662 ... 0.35049137 0.41640878 1.        ]]


In [6]:
import numpy as np

similarities_file = working_folder + "cosine_similarity_matrix.npy"
np.save(similarities_file, similarities)
print(f"Similarity matrix saved to {similarities_file}")

Similarity matrix saved to /content/drive/My Drive/TransformersCode/03-restaurant/Find_meals/cosine_similarity_matrix.npy
